spring.datasource.url=jdbc:mysql://localhost:3306/info_nlu_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.address=0.0.0.0
server.port=8080

# JWT
jwt.secret=NLU_INFO_APP_SECRET_KEY_2026_VERY_LONG_AND_SECURE_STRING_FOR_HS256
jwt.expiration=86400000

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bi2004npt@gmail.com
spring.mail.password=frdgtesggblqnlik
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true